const verbList = [
  {
    verbPresentSimple: 'be',
    verbPastSimple: 'was/were',
    verbPastParticiple: 'been',
    verbItalian: 'essere',
    verbTurkish: 'olmak',
    verbPresentSimplePronunciation: 'bi',
    verbPastSimplePronunciation: 'woz/wər',
    verbPastParticiplePronunciation: 'bin',
  },
  {
    verbPresentSimple: 'beat',
    verbPastSimple: 'beat',
    verbPastParticiple: 'beaten',
    verbItalian: 'battere',
    verbTurkish: 'yenmek',
    verbPresentSimplePronunciation: 'biːt',
    verbPastSimplePronunciation: 'bɛt',
    verbPastParticiplePronunciation: 'ˈbiːtn̩',
  },
  {
    verbPresentSimple: 'become',
    verbPastSimple: 'became',
    verbPastParticiple: 'become',
    verbItalian: 'diventare',
    verbTurkish: 'olmak, haline gelmek',
    verbPresentSimplePronunciation: 'bɪˈkʌm',
    verbPastSimplePronunciation: 'bɪˈkeɪm',
    verbPastParticiplePronunciation: 'bɪˈkʌm',
  },
  {
    verbPresentSimple: 'begin',
    verbPastSimple: 'began',
    verbPastParticiple: 'begun',
    verbItalian: 'cominciare',
    verbTurkish: 'başlamak',
    verbPresentSimplePronunciation: 'bɪˈɡɪn',
    verbPastSimplePronunciation: 'bɪˈɡæn',
    verbPastParticiplePronunciation: 'bɪˈɡʌn',
  },
  {
    verbPresentSimple: 'bend',
    verbPastSimple: 'bent',
    verbPastParticiple: 'bent',
    verbItalian: 'piegare',
    verbTurkish: 'bükülmek, eğilmek',
    verbPresentSimplePronunciation: 'bɛnd',
    verbPastSimplePronunciation: 'bɛnt',
    verbPastParticiplePronunciation: 'bɛnt',
  },
  {
    verbPresentSimple: 'bet',
    verbPastSimple: 'bet',
    verbPastParticiple: 'bet',
    verbItalian: 'scommettere',
    verbTurkish: 'bahse girmek',
    verbPresentSimplePronunciation: 'bɛt',
    verbPastSimplePronunciation: 'bɛt',
    verbPastParticiplePronunciation: 'bɛt',
  },
  {
    verbPresentSimple: 'bid',
    verbPastSimple: 'bid',
    verbPastParticiple: 'bid',
    verbItalian: "fare un'offerta",
    verbTurkish: 'teklif vermek',
    verbPresentSimplePronunciation: 'bɪd',
    verbPastSimplePronunciation: 'bɪd',
    verbPastParticiplePronunciation: 'bɪd',
  },
  {
    verbPresentSimple: 'bind',
    verbPastSimple: 'bound',
    verbPastParticiple: 'bound',
    verbItalian: 'legare',
    verbTurkish: 'bağlamak',
    verbPresentSimplePronunciation: 'baɪnd',
    verbPastSimplePronunciation: 'baʊnd',
    verbPastParticiplePronunciation: 'baʊnd',
  },
  {
    verbPresentSimple: 'bite',
    verbPastSimple: 'bit',
    verbPastParticiple: 'bitten',
    verbItalian: 'mordere',
    verbTurkish: 'ısırmak',
    verbPresentSimplePronunciation: 'baɪt',
    verbPastSimplePronunciation: 'bɪt',
    verbPastParticiplePronunciation: 'ˈbɪtn̩',
  },
  {
    verbPresentSimple: 'bleed',
    verbPastSimple: 'bled',
    verbPastParticiple: 'bled',
    verbItalian: 'sanguinare',
    verbTurkish: 'kanamak',
    verbPresentSimplePronunciation: 'bliːd',
    verbPastSimplePronunciation: 'blɛd',
    verbPastParticiplePronunciation: 'blɛd',
  },
  {
    verbPresentSimple: 'blow',
    verbPastSimple: 'blew',
    verbPastParticiple: 'blown',
    verbItalian: 'soffiare',
    verbTurkish: 'esmek, üflemek',
    verbPresentSimplePronunciation: 'bloʊ',
    verbPastSimplePronunciation: 'blu',
    verbPastParticiplePronunciation: 'bloʊn',
  },
  {
    verbPresentSimple: 'break',
    verbPastSimple: 'broke',
    verbPastParticiple: 'broken',
    verbItalian: 'rompere',
    verbTurkish: 'kırmak',
    verbPresentSimplePronunciation: 'breɪk',
    verbPastSimplePronunciation: 'broʊk',
    verbPastParticiplePronunciation: 'ˈbroʊkən',
  },
  {
    verbPresentSimple: 'breed',
    verbPastSimple: 'bred',
    verbPastParticiple: 'bred',
    verbItalian: 'allevare',
    verbTurkish: 'üremek',
    verbPresentSimplePronunciation: 'briːd',
    verbPastSimplePronunciation: 'brɛd',
    verbPastParticiplePronunciation: 'brɛd',
  },
  {
    verbPresentSimple: 'bring',
    verbPastSimple: 'brought',
    verbPastParticiple: 'brought',
    verbItalian: 'portare',
    verbTurkish: 'getirmek',
    verbPresentSimplePronunciation: 'brɪŋ',
    verbPastSimplePronunciation: 'brɔːt',
    verbPastParticiplePronunciation: 'brɔːt',
  },
  {
    verbPresentSimple: 'broadcast',
    verbPastSimple: 'broadcast/broadcasted',
    verbPastParticiple: 'broadcast/broadcasted',
    verbItalian: 'trasmettere',
    verbTurkish: 'yayınlamak',
    verbPresentSimplePronunciation: 'ˈbrɔːdkæst',
    verbPastSimplePronunciation: 'ˈbrɔːdkæst/ˈbrɔːdˌkæstɪd',
    verbPastParticiplePronunciation: 'ˈbrɔːdkæst/ˈbrɔːdˌkæstɪd',
  },
  {
    verbPresentSimple: 'build',
    verbPastSimple: 'built',
    verbPastParticiple: 'built',
    verbItalian: 'costruire',
    verbTurkish: 'inşa etmek',
    verbPresentSimplePronunciation: 'bɪld',
    verbPastSimplePronunciation: 'bɪlt',
    verbPastParticiplePronunciation: 'bɪlt',
  },
  {
    verbPresentSimple: 'burn',
    verbPastSimple: 'burned/burnt',
    verbPastParticiple: 'burned/burnt',
    verbItalian: 'bruciare',
    verbTurkish: 'yakmak',
    verbPresentSimplePronunciation: 'bɜːrn',
    verbPastSimplePronunciation: 'bɜːrnd/bɜːnt',
    verbPastParticiplePronunciation: 'bɜːrnd/bɜːnt',
  },
  {
    verbPresentSimple: 'burst',
    verbPastSimple: 'burst',
    verbPastParticiple: 'burst',
    verbItalian: 'scoppiare',
    verbTurkish: 'patlamak',
    verbPresentSimplePronunciation: 'bɜːrst',
    verbPastSimplePronunciation: 'bɜːrst',
    verbPastParticiplePronunciation: 'bɜːrst',
  },
  {
    verbPresentSimple: 'buy',
    verbPastSimple: 'bought',
    verbPastParticiple: 'bought',
    verbItalian: 'comprare',
    verbTurkish: 'satın almak',
    verbPresentSimplePronunciation: 'baɪ',
    verbPastSimplePronunciation: 'bɔːt',
    verbPastParticiplePronunciation: 'bɔːt',
  },
  {
    verbPresentSimple: 'cast',
    verbPastSimple: 'cast',
    verbPastParticiple: 'cast',
    verbItalian: 'gettare',
    verbTurkish: 'atmak',
    verbPresentSimplePronunciation: 'kæst',
    verbPastSimplePronunciation: 'kæst',
    verbPastParticiplePronunciation: 'kæst',
  },
  {
    verbPresentSimple: 'catch',
    verbPastSimple: 'caught',
    verbPastParticiple: 'caught',
    verbItalian: 'prendere',
    verbTurkish: 'yakalamak',
    verbPresentSimplePronunciation: 'kætʃ',
    verbPastSimplePronunciation: 'kɔːt',
    verbPastParticiplePronunciation: 'kɔːt',
  },
  {
    verbPresentSimple: 'choose',
    verbPastSimple: 'chose',
    verbPastParticiple: 'chosen',
    verbItalian: 'scegliere',
    verbTurkish: 'seçmek',
    verbPresentSimplePronunciation: 'tʃuːz',
    verbPastSimplePronunciation: 'tʃoʊz',
    verbPastParticiplePronunciation: 'ˈtʃoʊzən',
  },
  {
    verbPresentSimple: 'cling',
    verbPastSimple: 'clung',
    verbPastParticiple: 'clung',
    verbItalian: 'aggrapparsi',
    verbTurkish: 'tutunmak',
    verbPresentSimplePronunciation: 'klɪŋ',
    verbPastSimplePronunciation: 'klʌŋ',
    verbPastParticiplePronunciation: 'klʌŋ',
  },
  {
    verbPresentSimple: 'come',
    verbPastSimple: 'came',
    verbPastParticiple: 'come',
    verbItalian: 'venire',
    verbTurkish: 'gelmek',
    verbPresentSimplePronunciation: 'kʌm',
    verbPastSimplePronunciation: 'keɪm',
    verbPastParticiplePronunciation: 'kʌm',
  },
  {
    verbPresentSimple: 'cost',
    verbPastSimple: 'cost',
    verbPastParticiple: 'cost',
    verbItalian: 'costare',
    verbTurkish: 'mâl olmak',
    verbPresentSimplePronunciation: 'kɒst',
    verbPastSimplePronunciation: 'kɒst',
    verbPastParticiplePronunciation: 'kɒst',
  },
  {
    verbPresentSimple: 'count',
    verbPastSimple: 'counted',
    verbPastParticiple: 'counted',
    verbItalian: 'contare',
    verbTurkish: 'saymak',
    verbPresentSimplePronunciation: 'kaʊnt',
    verbPastSimplePronunciation: 'kaʊntɪd',
    verbPastParticiplePronunciation: 'kaʊntɪd',
  },
  {
    verbPresentSimple: 'creep',
    verbPastSimple: 'crept',
    verbPastParticiple: 'crept',
    verbItalian: 'strisciare',
    verbTurkish: 'sürünmek',
    verbPresentSimplePronunciation: 'kriːp',
    verbPastSimplePronunciation: 'krɛpt',
    verbPastParticiplePronunciation: 'krɛpt',
  },
  {
    verbPresentSimple: 'cut',
    verbPastSimple: 'cut',
    verbPastParticiple: 'cut',
    verbItalian: 'tagliare',
    verbTurkish: 'kesmek',
    verbPresentSimplePronunciation: 'kʌt',
    verbPastSimplePronunciation: 'kʌt',
    verbPastParticiplePronunciation: 'kʌt',
  },
  {
    verbPresentSimple: 'deal',
    verbPastSimple: 'dealt',
    verbPastParticiple: 'dealt',
    verbItalian: 'trattare',
    verbTurkish: 'ilgilenmek',
    verbPresentSimplePronunciation: 'diːl',
    verbPastSimplePronunciation: 'dɛlt',
    verbPastParticiplePronunciation: 'dɛlt',
  },
  {
    verbPresentSimple: 'dig',
    verbPastSimple: 'dug',
    verbPastParticiple: 'dug',
    verbItalian: 'scavare',
    verbTurkish: 'kazmak',
    verbPresentSimplePronunciation: 'dɪɡ',
    verbPastSimplePronunciation: 'dʌɡ',
    verbPastParticiplePronunciation: 'dʌɡ',
  },
  {
    verbPresentSimple: 'dive',
    verbPastSimple: 'dived/dove',
    verbPastParticiple: 'dived',
    verbItalian: 'tuffarsi',
    verbTurkish: 'dalma',
    verbPresentSimplePronunciation: 'daɪv',
    verbPastSimplePronunciation: 'daɪvd/doʊv',
    verbPastParticiplePronunciation: 'daɪvd',
  },
  {
    verbPresentSimple: 'do',
    verbPastSimple: 'did',
    verbPastParticiple: 'done',
    verbItalian: 'fare',
    verbTurkish: 'yapmak',
    verbPresentSimplePronunciation: 'duː',
    verbPastSimplePronunciation: 'dɪd',
    verbPastParticiplePronunciation: 'dʌn',
  },
  {
    verbPresentSimple: 'draw',
    verbPastSimple: 'drew',
    verbPastParticiple: 'drawn',
    verbItalian: 'disegnare',
    verbTurkish: 'çizmek',
    verbPresentSimplePronunciation: 'drɔː',
    verbPastSimplePronunciation: 'dru',
    verbPastParticiplePronunciation: 'drɔːn',
  },
  {
    verbPresentSimple: 'dream',
    verbPastSimple: 'dreamt/dreamed',
    verbPastParticiple: 'dreamt/dreamed',
    verbItalian: 'sognare',
    verbTurkish: 'rüya görmek',
    verbPresentSimplePronunciation: 'driːm',
    verbPastSimplePronunciation: 'dremt/drimd',
    verbPastParticiplePronunciation: 'dremt/drimd',
  },
  {
    verbPresentSimple: 'drink',
    verbPastSimple: 'drank',
    verbPastParticiple: 'drunk',
    verbItalian: 'bere',
    verbTurkish: 'içmek',
    verbPresentSimplePronunciation: 'drɪŋk',
    verbPastSimplePronunciation: 'dræŋk',
    verbPastParticiplePronunciation: 'drʌŋk',
  },
  {
    verbPresentSimple: 'drive',
    verbPastSimple: 'drove',
    verbPastParticiple: 'driven',
    verbItalian: 'guidare',
    verbTurkish: 'sürmek',
    verbPresentSimplePronunciation: 'draɪv',
    verbPastSimplePronunciation: 'droʊv',
    verbPastParticiplePronunciation: 'ˈdrɪvən',
  },
  {
    verbPresentSimple: 'dwell',
    verbPastSimple: 'dwelt/dwelled',
    verbPastParticiple: 'dwelt/dwelled',
    verbItalian: 'abitare',
    verbTurkish: 'oturmak',
    verbPresentSimplePronunciation: 'dwel',
    verbPastSimplePronunciation: 'dwɛlt/dwɛld',
    verbPastParticiplePronunciation: 'dwɛlt/dwɛld',
  },
  {
    verbPresentSimple: 'eat',
    verbPastSimple: 'ate',
    verbPastParticiple: 'eaten',
    verbItalian: 'mangiare',
    verbTurkish: 'yemek',
    verbPresentSimplePronunciation: 'iːt',
    verbPastSimplePronunciation: 'eɪt',
    verbPastParticiplePronunciation: 'ˈiːtn̩',
  },
  {
    verbPresentSimple: 'fall',
    verbPastSimple: 'fell',
    verbPastParticiple: 'fallen',
    verbItalian: 'cadere',
    verbTurkish: 'düşmek',
    verbPresentSimplePronunciation: 'fɔːl',
    verbPastSimplePronunciation: 'fɛl',
    verbPastParticiplePronunciation: 'ˈfɔːlən',
  },
  {
    verbPresentSimple: 'feed',
    verbPastSimple: 'fed',
    verbPastParticiple: 'fed',
    verbItalian: 'nutrire',
    verbTurkish: 'beslemek',
    verbPresentSimplePronunciation: 'fiːd',
    verbPastSimplePronunciation: 'fɛd',
    verbPastParticiplePronunciation: 'fɛd',
  },
  {
    verbPresentSimple: 'feel',
    verbPastSimple: 'felt',
    verbPastParticiple: 'felt',
    verbItalian: 'sentire',
    verbTurkish: 'hissedmek',
    verbPresentSimplePronunciation: 'fiːl',
    verbPastSimplePronunciation: 'fɛlt',
    verbPastParticiplePronunciation: 'fɛlt',
  },
  {
    verbPresentSimple: 'fight',
    verbPastSimple: 'fought',
    verbPastParticiple: 'fought',
    verbItalian: 'combattere',
    verbTurkish: 'savaşmak',
    verbPresentSimplePronunciation: 'faɪt',
    verbPastSimplePronunciation: 'fɔːt',
    verbPastParticiplePronunciation: 'fɔːt',
  },
  {
    verbPresentSimple: 'find',
    verbPastSimple: 'found',
    verbPastParticiple: 'found',
    verbItalian: 'trovare',
    verbTurkish: 'bulmak',
    verbPresentSimplePronunciation: 'faɪnd',
    verbPastSimplePronunciation: 'faʊnd',
    verbPastParticiplePronunciation: 'faʊnd',
  },
  {
    verbPresentSimple: 'flee',
    verbPastSimple: 'fled',
    verbPastParticiple: 'fled',
    verbItalian: 'fuggire',
    verbTurkish: 'kaçmak',
    verbPresentSimplePronunciation: 'fliː',
    verbPastSimplePronunciation: 'flɛd',
    verbPastParticiplePronunciation: 'flɛd',
  },
  {
    verbPresentSimple: 'fling',
    verbPastSimple: 'flung',
    verbPastParticiple: 'flung',
    verbItalian: 'lanciare',
    verbTurkish: 'fırlatmak',
    verbPresentSimplePronunciation: 'flɪŋ',
    verbPastSimplePronunciation: 'flʌŋ',
    verbPastParticiplePronunciation: 'flʌŋ',
  },
  {
    verbPresentSimple: 'fly',
    verbPastSimple: 'flew',
    verbPastParticiple: 'flown',
    verbItalian: 'volare',
    verbTurkish: 'uçmak',
    verbPresentSimplePronunciation: 'flaɪ',
    verbPastSimplePronunciation: 'flu',
    verbPastParticiplePronunciation: 'floʊn',
  },
  {
    verbPresentSimple: 'forbid',
    verbPastSimple: 'forbade/forbad',
    verbPastParticiple: 'forbidden',
    verbItalian: 'proibire',
    verbTurkish: 'yasaklamak',
    verbPresentSimplePronunciation: 'fərˈbɪd',
    verbPastSimplePronunciation: 'fərˈbæd/fɔrˈbæd',
    verbPastParticiplePronunciation: 'fərˈbɪdən',
  },
  {
    verbPresentSimple: 'forecast',
    verbPastSimple: 'forecast',
    verbPastParticiple: 'forecast',
    verbItalian: 'prevedere',
    verbTurkish: 'tahmin etmek',
    verbPresentSimplePronunciation: 'ˈfɔːrkæst',
    verbPastSimplePronunciation: 'ˈfɔːrkæst',
    verbPastParticiplePronunciation: 'ˈfɔːrkæst',
  },
  {
    verbPresentSimple: 'foresee',
    verbPastSimple: 'foresaw',
    verbPastParticiple: 'foreseen',
    verbItalian: 'prevedere',
    verbTurkish: 'ön görmek',
    verbPresentSimplePronunciation: 'fɔːrˈsiː',
    verbPastSimplePronunciation: 'fɔrˈsɔː',
    verbPastParticiplePronunciation: 'fɔːrˈsiːn',
  },
  {
    verbPresentSimple: 'forget',
    verbPastSimple: 'forgot',
    verbPastParticiple: 'forgotten',
    verbItalian: 'dimenticare',
    verbTurkish: 'unutmak',
    verbPresentSimplePronunciation: 'fərˈɡet',
    verbPastSimplePronunciation: 'fərˈɡɒt',
    verbPastParticiplePronunciation: 'fərˈɡɒtən',
  },
  {
    verbPresentSimple: 'forgive',
    verbPastSimple: 'forgave',
    verbPastParticiple: 'forgiven',
    verbItalian: 'perdonare',
    verbTurkish: 'affetmek',
    verbPresentSimplePronunciation: 'fərˈɡɪv',
    verbPastSimplePronunciation: 'fərˈɡeɪv',
    verbPastParticiplePronunciation: 'fərˈɡɪvən',
  },
  {
    verbPresentSimple: 'forsake',
    verbPastSimple: 'forsook',
    verbPastParticiple: 'forsaken',
    verbItalian: 'abbandonare',
    verbTurkish: 'terk etmek',
    verbPresentSimplePronunciation: 'fɔrˈseɪk',
    verbPastSimplePronunciation: 'fɔrˈsʊk',
    verbPastParticiplePronunciation: 'fɔrˈseɪkən',
  },
  {
    verbPresentSimple: 'freeze',
    verbPastSimple: 'froze',
    verbPastParticiple: 'frozen',
    verbItalian: 'gelare',
    verbTurkish: 'donmak',
    verbPresentSimplePronunciation: 'friːz',
    verbPastSimplePronunciation: 'froʊz',
    verbPastParticiplePronunciation: 'ˈfroʊzən',
  },
  {
    verbPresentSimple: 'get',
    verbPastSimple: 'got',
    verbPastParticiple: 'got/gotten',
    verbItalian: 'ottenere',
    verbTurkish: 'almak',
    verbPresentSimplePronunciation: 'ɡet',
    verbPastSimplePronunciation: 'ɡɒt',
    verbPastParticiplePronunciation: 'ɡɒt/ˈɡɒtən',
  },
  {
    verbPresentSimple: 'give',
    verbPastSimple: 'gave',
    verbPastParticiple: 'given',
    verbItalian: 'dare',
    verbTurkish: 'vermek',
    verbPresentSimplePronunciation: 'ɡɪv',
    verbPastSimplePronunciation: 'ɡeɪv',
    verbPastParticiplePronunciation: 'ˈɡɪvən',
  },
  {
    verbPresentSimple: 'go',
    verbPastSimple: 'went',
    verbPastParticiple: 'gone',
    verbItalian: 'andare',
    verbTurkish: 'gitmek',
    verbPresentSimplePronunciation: 'ɡoʊ',
    verbPastSimplePronunciation: 'wɛnt',
    verbPastParticiplePronunciation: 'ɡɒn',
  },
  {
    verbPresentSimple: 'grind',
    verbPastSimple: 'ground',
    verbPastParticiple: 'ground',
    verbItalian: 'macinare',
    verbTurkish: 'öğütmek',
    verbPresentSimplePronunciation: 'ɡraɪnd',
    verbPastSimplePronunciation: 'ɡraʊnd',
    verbPastParticiplePronunciation: 'ɡraʊnd',
  },
  {
    verbPresentSimple: 'grow',
    verbPastSimple: 'grew',
    verbPastParticiple: 'grown',
    verbItalian: 'crescere',
    verbTurkish: 'büyümek',
    verbPresentSimplePronunciation: 'ɡroʊ',
    verbPastSimplePronunciation: 'ɡru',
    verbPastParticiplePronunciation: 'ɡroʊn',
  },
  {
    verbPresentSimple: 'hang',
    verbPastSimple: 'hung',
    verbPastParticiple: 'hung',
    verbItalian: 'appendere',
    verbTurkish: 'asmak',
    verbPresentSimplePronunciation: 'hæŋ',
    verbPastSimplePronunciation: 'hʌŋ',
    verbPastParticiplePronunciation: 'hʌŋ',
  },
  {
    verbPresentSimple: 'have',
    verbPastSimple: 'had',
    verbPastParticiple: 'had',
    verbItalian: 'avere',
    verbTurkish: 'sahip olmak',
    verbPresentSimplePronunciation: 'hæv',
    verbPastSimplePronunciation: 'hæd',
    verbPastParticiplePronunciation: 'hæd',
  },
  {
    verbPresentSimple: 'hear',
    verbPastSimple: 'heard',
    verbPastParticiple: 'heard',
    verbItalian: 'sentire',
    verbTurkish: 'duymak',
    verbPresentSimplePronunciation: 'hɪr',
    verbPastSimplePronunciation: 'hɜːd',
    verbPastParticiplePronunciation: 'hɜːd',
  },
  {
    verbPresentSimple: 'hide',
    verbPastSimple: 'hid',
    verbPastParticiple: 'hidden',
    verbItalian: 'nascondere',
    verbTurkish: 'saklamak',
    verbPresentSimplePronunciation: 'haɪd',
    verbPastSimplePronunciation: 'hɪd',
    verbPastParticiplePronunciation: 'ˈhɪdən',
  },
  {
    verbPresentSimple: 'hit',
    verbPastSimple: 'hit',
    verbPastParticiple: 'hit',
    verbItalian: 'colpire',
    verbTurkish: 'vurmak',
    verbPresentSimplePronunciation: 'hɪt',
    verbPastSimplePronunciation: 'hɪt',
    verbPastParticiplePronunciation: 'hɪt',
  },
  {
    verbPresentSimple: 'hold',
    verbPastSimple: 'held',
    verbPastParticiple: 'held',
    verbItalian: 'tenere',
    verbTurkish: 'tutmak',
    verbPresentSimplePronunciation: 'hoʊld',
    verbPastSimplePronunciation: 'hɛld',
    verbPastParticiple: 'hɛld',
  },
  {
    verbPresentSimple: 'hurt',
    verbPastSimple: 'hurt',
    verbPastParticiple: 'hurt',
    verbItalian: 'ferire',
    verbTurkish: 'hurt',
    verbPresentSimplePronunciation: 'hɜːrt',
    verbPastSimplePronunciation: 'hɜːrt',
    verbPastParticiplePronunciation: 'hɜːrt',
  },
  {
    verbPresentSimple: 'keep',
    verbPastSimple: 'kept',
    verbPastParticiple: 'kept',
    verbItalian: 'tenere',
    verbTurkish: 'saklamak, korumak',
    verbPresentSimplePronunciation: 'kiːp',
    verbPastSimplePronunciation: 'kɛpt',
    verbPastParticiplePronunciation: 'kɛpt',
  },
  {
    verbPresentSimple: 'kneel',
    verbPastSimple: 'knelt/kneeled',
    verbPastParticiple: 'knelt/kneeled',
    verbItalian: 'inginocchiarsi',
    verbTurkish: 'diz çökmek',
    verbPresentSimplePronunciation: 'niːl',
    verbPastSimplePronunciation: 'nɛlt/niːld',
    verbPastParticiplePronunciation: 'nɛlt/niːld',
  },
  {
    verbPresentSimple: 'knit',
    verbPastSimple: 'knit/knitted',
    verbPastParticiple: 'knit/knitted',
    verbItalian: 'lavorare a maglia',
    verbTurkish: 'örmek',
    verbPresentSimplePronunciation: 'nɪt',
    verbPastSimplePronunciation: 'nɪt/ˈnɪtɪd',
    verbPastParticiplePronunciation: 'nɪt/ˈnɪtɪd',
  },
  {
    verbPresentSimple: 'know',
    verbPastSimple: 'knew',
    verbPastParticiple: 'known',
    verbItalian: 'sapere',
    verbTurkish: 'bilmek',
    verbPresentSimplePronunciation: 'noʊ',
    verbPastSimplePronunciation: 'njuː',
    verbPastParticiplePronunciation: 'noʊn',
  },
  {
    verbPresentSimple: 'lay',
    verbPastSimple: 'laid',
    verbPastParticiple: 'laid',
    verbItalian: 'posare',
    verbTurkish: 'yerleştirmek',
    verbPresentSimplePronunciation: 'leɪ',
    verbPastSimplePronunciation: 'leɪd',
    verbPastParticiplePronunciation: 'leɪd',
  },
  {
    verbPresentSimple: 'lead',
    verbPastSimple: 'led',
    verbPastParticiple: 'led',
    verbItalian: 'condurre',
    verbTurkish: 'yönetmek',
    verbPresentSimplePronunciation: 'liːd',
    verbPastSimplePronunciation: 'lɛd',
    verbPastParticiplePronunciation: 'lɛd',
  },
  {
    verbPresentSimple: 'learn',
    verbPastSimple: 'learned/learnt',
    verbPastParticiple: 'learned/learnt',
    verbItalian: 'imparare',
    verbTurkish: 'öğrenmek',
    verbPresentSimplePronunciation: 'lɜːrn',
    verbPastSimplePronunciation: 'lɜːrnd/lɜːnt',
    verbPastParticiplePronunciation: 'lɜːrnd/lɜːnt',
  },
  {
    verbPresentSimple: 'leave',
    verbPastSimple: 'left',
    verbPastParticiple: 'left',
    verbItalian: 'lasciare',
    verbTurkish: 'ayrılmak, terketmek',
    verbPresentSimplePronunciation: 'liːv',
    verbPastSimplePronunciation: 'lɛft',
    verbPastParticiplePronunciation: 'lɛft',
  },
  {
    verbPresentSimple: 'lend',
    verbPastSimple: 'lent',
    verbPastParticiple: 'lent',
    verbItalian: 'prestare',
    verbTurkish: 'ödünç vermek',
    verbPresentSimplePronunciation: 'lɛnd',
    verbPastSimplePronunciation: 'lɛnt',
    verbPastParticiplePronunciation: 'lɛnt',
  },
  {
    verbPresentSimple: 'let',
    verbPastSimple: 'let',
    verbPastParticiple: 'let',
    verbItalian: 'lasciare',
    verbTurkish: 'izin vermek',
    verbPresentSimplePronunciation: 'lɛt',
    verbPastSimplePronunciation: 'lɛt',
    verbPastParticiplePronunciation: 'lɛt',
  },
  {
    verbPresentSimple: 'lie',
    verbPastSimple: 'lay',
    verbPastParticiple: 'lain',
    verbItalian: 'stare',
    verbTurkish: 'uzanmak',
    verbPresentSimplePronunciation: 'laɪ',
    verbPastSimplePronunciation: 'leɪ',
    verbPastParticiplePronunciation: 'leɪn',
  },
  {
    verbPresentSimple: 'light',
    verbPastSimple: 'lit/lighted',
    verbPastParticiple: 'lit/lighted',
    verbItalian: 'accendere',
    verbTurkish: 'ışıklandırmak',
    verbPresentSimplePronunciation: 'laɪt',
    verbPastSimplePronunciation: 'lɪt/ˈlaɪtɪd',
    verbPastParticiplePronunciation: 'lɪt/ˈlaɪtɪd',
  },
  {
    verbPresentSimple: 'lose',
    verbPastSimple: 'lost',
    verbPastParticiple: 'lost',
    verbItalian: 'perdere',
    verbTurkish: 'kaybetmek',
    verbPresentSimplePronunciation: 'luːz',
    verbPastSimplePronunciation: 'lɒst',
    verbPastParticiplePronunciation: 'lɒst',
  },
  {
    verbPresentSimple: 'mean',
    verbPastSimple: 'meant',
    verbPastParticiple: 'meant',
    verbItalian: 'significare',
    verbTurkish: 'anlamına gelmek',
    verbPresentSimplePronunciation: 'miːn',
    verbPastSimplePronunciation: 'mɛnt',
    verbPastParticiplePronunciation: 'mɛnt',
  },
  {
    verbPresentSimple: 'meet',
    verbPastSimple: 'met',
    verbPastParticiple: 'met',
    verbItalian: 'incontrare',
    verbTurkish: 'tanışmak, buluşmak',
    verbPresentSimplePronunciation: 'miːt',
    verbPastSimplePronunciation: 'mɛt',
    verbPastParticiplePronunciation: 'mɛt',
  },
  {
    verbPresentSimple: 'mow',
    verbPastSimple: 'mowed',
    verbPastParticiple: 'mown/mowed',
    verbItalian: 'falciare',
    verbTurkish: 'biçmek',
    verbPresentSimplePronunciation: 'moʊ',
    verbPastSimplePronunciation: 'moʊd',
    verbPastParticiplePronunciation: 'moʊn/moʊd',
  },
  {
    verbPresentSimple: 'pay',
    verbPastSimple: 'paid',
    verbPastParticiple: 'paid',
    verbItalian: 'pagare',
    verbTurkish: 'ödemek',
    verbPresentSimplePronunciation: 'peɪ',
    verbPastSimplePronunciation: 'peɪd',
    verbPastParticiplePronunciation: 'peɪd',
  },
  {
    verbPresentSimple: 'put',
    verbPastSimple: 'put',
    verbPastParticiple: 'put',
    verbItalian: 'mettere',
    verbTurkish: 'koymak',
    verbPresentSimplePronunciation: 'pʊt',
    verbPastSimplePronunciation: 'pʊt',
    verbPastParticiplePronunciation: 'pʊt',
  },
  {
    verbPresentSimple: 'read',
    verbPastSimple: 'read',
    verbPastParticiple: 'read',
    verbItalian: 'leggere',
    verbTurkish: 'okumak',
    verbPresentSimplePronunciation: 'riːd',
    verbPastSimplePronunciation: 'rɛd',
    verbPastParticiplePronunciation: 'rɛd',
  },
  {
    verbPresentSimple: 'ride',
    verbPastSimple: 'rode',
    verbPastParticiple: 'ridden',
    verbItalian: 'andare a cavallo',
    verbTurkish: 'binmek',
    verbPresentSimplePronunciation: 'raɪd',
    verbPastSimplePronunciation: 'roʊd',
    verbPastParticiplePronunciation: 'ˈrɪdən',
  },
  {
    verbPresentSimple: 'rise',
    verbPastSimple: 'rose',
    verbPastParticiple: 'risen',
    verbItalian: 'alzarsi',
    verbTurkish: 'yükselmek',
    verbPresentSimplePronunciation: 'raɪz',
    verbPastSimplePronunciation: 'roʊz',
    verbPastParticiplePronunciation: 'ˈrɪzən',
  },
  {
    verbPresentSimple: 'run',
    verbPastSimple: 'ran',
    verbPastParticiple: 'run',
    verbItalian: 'correre',
    verbTurkish: 'koşmak',
    verbPresentSimplePronunciation: 'rʌn',
    verbPastSimplePronunciation: 'ræn',
    verbPastParticiplePronunciation: 'rʌn',
  },
  {
    verbPresentSimple: 'saw',
    verbPastSimple: 'sawed',
    verbPastParticiple: 'sawn/sawed',
    verbItalian: 'seghettare',
    verbTurkish: 'testere ile kesmek',
    verbPresentSimplePronunciation: 'sɔː',
    verbPastSimplePronunciation: 'sɔːd',
    verbPastParticiplePronunciation: 'sɔːn/sɔːd',
  },
  {
    verbPresentSimple: 'say',
    verbPastSimple: 'said',
    verbPastParticiple: 'said',
    verbItalian: 'dire',
    verbTurkish: 'söylemek',
    verbPresentSimplePronunciation: 'seɪ',
    verbPastSimplePronunciation: 'sɛd',
    verbPastParticiplePronunciation: 'sɛd',
  },
  {
    verbPresentSimple: 'see',
    verbPastSimple: 'saw',
    verbPastParticiple: 'seen',
    verbItalian: 'vedere',
    verbTurkish: 'görmek',
    verbPresentSimplePronunciation: 'siː',
    verbPastSimplePronunciation: 'sɔː',
    verbPastParticiplePronunciation: 'siːn',
  },
  {
    verbPresentSimple: 'seek',
    verbPastSimple: 'sought',
    verbPastParticiple: 'sought',
    verbItalian: 'cercare',
    verbTurkish: 'araştırmak, aramak',
    verbPresentSimplePronunciation: 'siːk',
    verbPastSimplePronunciation: 'sɔːt',
    verbPastParticiplePronunciation: 'sɔːt',
  },
  {
    verbPresentSimple: 'sell',
    verbPastSimple: 'sold',
    verbPastParticiple: 'sold',
    verbItalian: 'vendere',
    verbTurkish: 'satmak',
    verbPresentSimplePronunciation: 'sɛl',
    verbPastSimplePronunciation: 'soʊld',
    verbPastParticiplePronunciation: 'soʊld',
  },
  {
    verbPresentSimple: 'set',
    verbPastSimple: 'set',
    verbPastParticiple: 'set',
    verbItalian: 'mettere',
    verbTurkish: 'ayarlamak, koymak',
    verbPresentSimplePronunciation: 'sɛt',
    verbPastSimplePronunciation: 'sɛt',
    verbPastParticiplePronunciation: 'sɛt',
  },
  {
    verbPresentSimple: 'sew',
    verbPastSimple: 'sewed',
    verbPastParticiple: 'sewn/sewed',
    verbItalian: 'cucire',
    verbTurkish: 'dikiş dikmek',
    verbPresentSimplePronunciation: 'səʊ',
    verbPastSimplePronunciation: 'səʊd',
    verbPastParticiplePronunciation: 'səʊn/səʊd',
  },
  {
    verbPresentSimple: 'shake',
    verbPastSimple: 'shook',
    verbPastParticiple: 'shaken',
    verbItalian: 'scuotere',
    verbTurkish: 'sarsmak, çalkalamak',
    verbPresentSimplePronunciation: 'ʃeɪk',
    verbPastSimplePronunciation: 'ʃʊk',
    verbPastParticiplePronunciation: 'ˈʃeɪkən',
  },
  {
    verbPresentSimple: 'shave',
    verbPastSimple: 'shaved',
    verbPastParticiple: 'shaved/shaven',
    verbItalian: 'rasare',
    verbTurkish: 'tıraş olmak',
    verbPresentSimplePronunciation: 'ʃeɪv',
    verbPastSimplePronunciation: 'ʃeɪvd',
    verbPastParticiplePronunciation: 'ʃeɪvd/ˈʃeɪvən',
  },
  {
    verbPresentSimple: 'shear',
    verbPastSimple: 'sheared',
    verbPastParticiple: 'shorn/sheared',
    verbItalian: 'tosare',
    verbTurkish: 'kırpmak, keçi kılı tıraşı yapmak',
    verbPresentSimplePronunciation: 'ʃɪr',
    verbPastSimplePronunciation: 'ʃɛrd',
    verbPastParticiplePronunciation: 'ʃɔːn/ʃɛrd',
  },
  {
    verbPresentSimple: 'shed',
    verbPastSimple: 'shed',
    verbPastParticiple: 'shed',
    verbItalian: 'versare (lacrima)',
    verbTurkish: 'dökmek, saçmak',
    verbPresentSimplePronunciation: 'ʃɛd',
    verbPastSimplePronunciation: 'ʃɛd',
    verbPastParticiplePronunciation: 'ʃɛd',
  },
  {
    verbPresentSimple: 'shoot',
    verbPastSimple: 'shot',
    verbPastParticiple: 'shot',
    verbItalian: 'sparare',
    verbTurkish: 'ateş etmek, vurmak',
    verbPresentSimplePronunciation: 'ʃuːt',
    verbPastSimplePronunciation: 'ʃɒt',
    verbPastParticiplePronunciation: 'ʃɒt',
  },
  {
    verbPresentSimple: 'show',
    verbPastSimple: 'showed',
    verbPastParticiple: 'shown/showed',
    verbItalian: 'mostrare',
    verbTurkish: 'göstermek',
    verbPresentSimplePronunciation: 'ʃəʊ',
    verbPastSimplePronunciation: 'ʃəʊd',
    verbPastParticiplePronunciation: 'ʃəʊn/ʃəʊd',
  },
  {
    verbPresentSimple: 'shrink',
    verbPastSimple: 'shrank/shrunk',
    verbPastParticiple: 'shrunk',
    verbItalian: 'rinculare',
    verbTurkish: 'küçülmek, çekmek',
    verbPresentSimplePronunciation: 'ʃrɪŋk',
    verbPastSimplePronunciation: 'ʃræŋk/ʃrʌŋk',
    verbPastParticiplePronunciation: 'ʃrʌŋk',
  },
  {
    verbPresentSimple: 'shut',
    verbPastSimple: 'shut',
    verbPastParticiple: 'shut',
    verbItalian: 'chiudere',
    verbTurkish: 'kapatmak',
    verbPresentSimplePronunciation: 'ʃʌt',
    verbPastSimplePronunciation: 'ʃʌt',
    verbPastParticiplePronunciation: 'ʃʌt',
  },
  {
    verbPresentSimple: 'sing',
    verbPastSimple: 'sang',
    verbPastParticiple: 'sung',
    verbItalian: 'cantare',
    verbTurkish: 'şarkı söylemek',
    verbPresentSimplePronunciation: 'sɪŋ',
    verbPastSimplePronunciation: 'sæŋ',
    verbPastParticiplePronunciation: 'sʌŋ',
  },
  {
    verbPresentSimple: 'sink',
    verbPastSimple: 'sank/sunk',
    verbPastParticiple: 'sunk',
    verbItalian: 'affondare',
    verbTurkish: 'batmak',
    verbPresentSimplePronunciation: 'sɪŋk',
    verbPastSimplePronunciation: 'sæŋk/sʌŋk',
    verbPastParticiplePronunciation: 'sʌŋk',
  },
  {
    verbPresentSimple: 'sit',
    verbPastSimple: 'sat',
    verbPastParticiple: 'sat',
    verbItalian: 'sedersi',
    verbTurkish: 'oturmak',
    verbPresentSimplePronunciation: 'sɪt',
    verbPastSimplePronunciation: 'sæt',
    verbPastParticiplePronunciation: 'sæt',
  },
  {
    verbPresentSimple: 'sleep',
    verbPastSimple: 'slept',
    verbPastParticiple: 'slept',
    verbItalian: 'dormire',
    verbTurkish: 'uyumak',
    verbPresentSimplePronunciation: 'sliːp',
    verbPastSimplePronunciation: 'slɛpt',
    verbPastParticiplePronunciation: 'slɛpt',
  },
  {
    verbPresentSimple: 'slide',
    verbPastSimple: 'slid',
    verbPastParticiple: 'slid',
    verbItalian: 'scivolare',
    verbTurkish: 'kaymak, kaydırmak',
    verbPresentSimplePronunciation: 'slaɪd',
    verbPastSimplePronunciation: 'slɪd',
    verbPastParticiplePronunciation: 'slɪd',
  },
  {
    verbPresentSimple: 'smell',
    verbPastSimple: 'smelled/smelt',
    verbPastParticiple: 'smelled/smelt',
    verbItalian: 'odorare',
    verbTurkish: 'koklamak, kokusu olmak',
    verbPresentSimplePronunciation: 'smɛl',
    verbPastSimplePronunciation: 'smɛld/smɛlt',
    verbPastParticiplePronunciation: 'smɛld/smɛlt',
  },
  {
    verbPresentSimple: 'smite',
    verbPastSimple: 'smote',
    verbPastParticiple: 'smitten',
    verbItalian: 'colpire',
    verbTurkish: 'vurmak, darbe vurmak',
    verbPresentSimplePronunciation: 'smaɪt',
    verbPastSimplePronunciation: 'smoʊt',
    verbPastParticiplePronunciation: 'ˈsmɪtn',
  },
  {
    verbPresentSimple: 'sow',
    verbPastSimple: 'sowed',
    verbPastParticiple: 'sown/sowed',
    verbItalian: 'seminare',
    verbTurkish: 'tohum ekmek',
    verbPresentSimplePronunciation: 'soʊ',
    verbPastSimplePronunciation: 'soʊd',
    verbPastParticiplePronunciation: 'soʊn/soʊd',
  },
  {
    verbPresentSimple: 'speak',
    verbPastSimple: 'spoke',
    verbPastParticiple: 'spoken',
    verbItalian: 'parlare',
    verbTurkish: 'konuşmak',
    verbPresentSimplePronunciation: 'spiːk',
    verbPastSimplePronunciation: 'spoʊk',
    verbPastParticiplePronunciation: 'ˈspoʊkən',
  },
  {
    verbPresentSimple: 'speed',
    verbPastSimple: 'sped/speeded',
    verbPastParticiple: 'sped/speeded',
    verbItalian: 'andare veloce',
    verbTurkish: 'hızlanmak',
    verbPresentSimplePronunciation: 'spiːd',
    verbPastSimplePronunciation: 'spɛd/ˈspiːdɪd',
    verbPastParticiplePronunciation: 'spɛd/ˈspiːdɪd',
  },
  {
    verbPresentSimple: 'spell',
    verbPastSimple: 'spelled/spelt',
    verbPastParticiple: 'spelled/spelt',
    verbItalian: 'dechifrare',
    verbTurkish: 'hecelemek, doğru yazmak',
    verbPresentSimplePronunciation: 'spɛl',
    verbPastSimplePronunciation: 'spɛld/spɛlt',
    verbPastParticiplePronunciation: 'spɛld/spɛlt',
  },
  {
    verbPresentSimple: 'spend',
    verbPastSimple: 'spent',
    verbPastParticiple: 'spent',
    verbItalian: 'spendere',
    verbTurkish: 'harcamak, geçirmek',
    verbPresentSimplePronunciation: 'spɛnd',
    verbPastSimplePronunciation: 'spɛnt',
    verbPastParticiplePronunciation: 'spɛnt',
  },
  {
    verbPresentSimple: 'spill',
    verbPastSimple: 'spilled/spilt',
    verbPastParticiple: 'spilled/spilt',
    verbItalian: 'versare (liquido)',
    verbTurkish: 'dökmek',
    verbPresentSimplePronunciation: 'spɪl',
    verbPastSimplePronunciation: 'spɪld/spɪlt',
    verbPastParticiplePronunciation: 'spɪld/spɪlt',
  },
  {
    verbPresentSimple: 'spin',
    verbPastSimple: 'spun',
    verbPastParticiple: 'spun',
    verbItalian: 'filare',
    verbTurkish: 'döndürmek, çevirmek',
    verbPresentSimplePronunciation: 'spɪn',
    verbPastSimplePronunciation: 'spʌn',
    verbPastParticiplePronunciation: 'spʌn',
  },
  {
    verbPresentSimple: 'spit',
    verbPastSimple: 'spit/spat',
    verbPastParticiple: 'spit/spat',
    verbItalian: 'sputare',
    verbTurkish: 'tükürmek',
    verbPresentSimplePronunciation: 'spɪt',
    verbPastSimplePronunciation: 'spɪt/spæt',
    verbPastParticiplePronunciation: 'spɪt/spæt',
  },
  {
    verbPresentSimple: 'split',
    verbPastSimple: 'split',
    verbPastParticiple: 'split',
    verbItalian: 'dividere',
    verbTurkish: 'bölmek, ayırmak',
    verbPresentSimplePronunciation: 'splɪt',
    verbPastSimplePronunciation: 'splɪt',
    verbPastParticiplePronunciation: 'splɪt',
  },
  {
    verbPresentSimple: 'spread',
    verbPastSimple: 'spread',
    verbPastParticiple: 'spread',
    verbItalian: 'diffondere',
    verbTurkish: 'yayılmak, yaymak',
    verbPresentSimplePronunciation: 'sprɛd',
    verbPastSimplePronunciation: 'sprɛd',
    verbPastParticiplePronunciation: 'sprɛd',
  },
  {
    verbPresentSimple: 'spring',
    verbPastSimple: 'sprang/sprung',
    verbPastParticiple: 'sprung',
    verbItalian: 'saltare',
    verbTurkish: 'sıçramak, fışkırmak',
    verbPresentSimplePronunciation: 'sprɪŋ',
    verbPastSimplePronunciation: 'spræŋ/sprʌŋ',
    verbPastParticiplePronunciation: 'sprʌŋ',
  },
  {
    verbPresentSimple: 'stand',
    verbPastSimple: 'stood',
    verbPastParticiple: 'stood',
    verbItalian: 'stare in piedi',
    verbTurkish: 'durmak, ayakta durmak',
    verbPresentSimplePronunciation: 'stænd',
    verbPastSimplePronunciation: 'stʊd',
    verbPastParticiplePronunciation: 'stʊd',
  },
  {
    verbPresentSimple: 'steal',
    verbPastSimple: 'stole',
    verbPastParticiple: 'stolen',
    verbItalian: 'rubare',
    verbTurkish: 'çalmak',
    verbPresentSimplePronunciation: 'stiːl',
    verbPastSimplePronunciation: 'stoʊl',
    verbPastParticiplePronunciation: 'ˈstoʊlən',
  },
  {
    verbPresentSimple: 'stick',
    verbPastSimple: 'stuck',
    verbPastParticiple: 'stuck',
    verbItalian: 'attaccare',
    verbTurkish: 'yapışmak, saplamak',
    verbPresentSimplePronunciation: 'stɪk',
    verbPastSimplePronunciation: 'stʌk',
    verbPastParticiplePronunciation: 'stʌk',
  },
  {
    verbPresentSimple: 'sting',
    verbPastSimple: 'stung',
    verbPastParticiple: 'stung',
    verbItalian: 'pungere',
    verbTurkish: 'sokmak',
    verbPresentSimplePronunciation: 'stɪŋ',
    verbPastSimplePronunciation: 'stʌŋ',
    verbPastParticiplePronunciation: 'stʌŋ',
  },
  {
    verbPresentSimple: 'stink',
    verbPastSimple: 'stank/stunk',
    verbPastParticiple: 'stunk',
    verbItalian: 'puzzare',
    verbTurkish: 'kokmak',
    verbPresentSimplePronunciation: 'stɪŋk',
    verbPastSimplePronunciation: 'stæŋk/stʌŋk',
    verbPastParticiplePronunciation: 'stʌŋk',
  },
  {
    verbPresentSimple: 'strike',
    verbPastSimple: 'struck',
    verbPastParticiple: 'struck',
    verbItalian: 'colpire',
    verbTurkish: 'vurmak, grev yapmak',
    verbPresentSimplePronunciation: 'straɪk',
    verbPastSimplePronunciation: 'strʌk',
    verbPastParticiplePronunciation: 'strʌk',
  },
  {
    verbPresentSimple: 'strive',
    verbPastSimple: 'strove/strived',
    verbPastParticiple: 'striven/strived',
    verbItalian: 'sforzarsi',
    verbTurkish: 'çaba sarfetmek, uğraşmak',
    verbPresentSimplePronunciation: 'straɪv',
    verbPastSimplePronunciation: 'stroʊv/straɪvd',
    verbPastParticiplePronunciation: 'ˈstrɪvən/straɪvd',
  },
  {
    verbPresentSimple: 'swear',
    verbPastSimple: 'swore',
    verbPastParticiple: 'sworn',
    verbItalian: 'giurare',
    verbTurkish: 'yemin etmek',
    verbPresentSimplePronunciation: 'swɛr',
    verbPastSimplePronunciation: 'swɔr',
    verbPastParticiplePronunciation: 'swɔrn',
  },
  {
    verbPresentSimple: 'sweep',
    verbPastSimple: 'swept',
    verbPastParticiple: 'swept',
    verbItalian: 'spazzare',
    verbTurkish: 'süpürmek',
    verbPresentSimplePronunciation: 'swiːp',
    verbPastSimplePronunciation: 'swɛpt',
    verbPastParticiplePronunciation: 'swɛpt',
  },
  {
    verbPresentSimple: 'swell',
    verbPastSimple: 'swelled',
    verbPastParticiple: 'swollen/swelled',
    verbItalian: 'gonfiare',
    verbTurkish: 'şişmek, kabarmak',
    verbPresentSimplePronunciation: 'swɛl',
    verbPastSimplePronunciation: 'swɛld',
    verbPastParticiplePronunciation: 'ˈswɛloʊn/swɛld',
  },
  {
    verbPresentSimple: 'swim',
    verbPastSimple: 'swam',
    verbPastParticiple: 'swum',
    verbItalian: 'nuotare',
    verbTurkish: 'yüzmek',
    verbPresentSimplePronunciation: 'swɪm',
    verbPastSimplePronunciation: 'swæm',
    verbPastParticiplePronunciation: 'swʌm',
  },
  {
    verbPresentSimple: 'swing',
    verbPastSimple: 'swung',
    verbPastParticiple: 'swung',
    verbItalian: 'oscillare',
    verbTurkish: 'sallanmak, sallamak',
    verbPresentSimplePronunciation: 'swɪŋ',
    verbPastSimplePronunciation: 'swʌŋ',
    verbPastParticiplePronunciation: 'swʌŋ',
  },
  {
    verbPresentSimple: 'take',
    verbPastSimple: 'took',
    verbPastParticiple: 'taken',
    verbItalian: 'prendere',
    verbTurkish: 'almak, götürmek',
    verbPresentSimplePronunciation: 'teɪk',
    verbPastSimplePronunciation: 'tʊk',
    verbPastParticiplePronunciation: 'ˈteɪkən',
  },
  {
    verbPresentSimple: 'teach',
    verbPastSimple: 'taught',
    verbPastParticiple: 'taught',
    verbItalian: 'insegnare',
    verbTurkish: 'öğretmek, ders vermek',
    verbPresentSimplePronunciation: 'titʃ',
    verbPastSimplePronunciation: 'tɔːt',
    verbPastParticiplePronunciation: 'tɔːt',
  },
  {
    verbPresentSimple: 'tear',
    verbPastSimple: 'tore',
    verbPastParticiple: 'torn',
    verbItalian: 'strappare',
    verbTurkish: 'yırtmak',
    verbPresentSimplePronunciation: 'tɪr',
    verbPastSimplePronunciation: 'tɔr',
    verbPastParticiplePronunciation: 'tɔrn',
  },
  {
    verbPresentSimple: 'tell',
    verbPastSimple: 'told',
    verbPastParticiple: 'told',
    verbItalian: 'dire',
    verbTurkish: 'söylemek',
    verbPresentSimplePronunciation: 'tɛl',
    verbPastSimplePronunciation: 'toʊld',
    verbPastParticiplePronunciation: 'toʊld',
  },
  {
    verbPresentSimple: 'think',
    verbPastSimple: 'thought',
    verbPastParticiple: 'thought',
    verbItalian: 'pensare',
    verbTurkish: 'düşünmek',
    verbPresentSimplePronunciation: 'θɪŋk',
    verbPastSimplePronunciation: 'θɔːt',
    verbPastParticiplePronunciation: 'θɔːt',
  },
  {
    verbPresentSimple: 'throw',
    verbPastSimple: 'threw',
    verbPastParticiple: 'thrown',
    verbItalian: 'gettare',
    verbTurkish: 'atmak, fırlatmak',
    verbPresentSimplePronunciation: 'θroʊ',
    verbPastSimplePronunciation: 'θru',
    verbPastParticiplePronunciation: 'θroʊn',
  },
  {
    verbPresentSimple: 'thrust',
    verbPastSimple: 'thrust',
    verbPastParticiple: 'thrust',
    verbItalian: 'spingere',
    verbTurkish: 'itmek, sokmak',
    verbPresentSimplePronunciation: 'θrʌst',
    verbPastSimplePronunciation: 'θrʌst',
    verbPastParticiplePronunciation: 'θrʌst',
  },
  {
    verbPresentSimple: 'undergo',
    verbPastSimple: 'underwent',
    verbPastParticiple: 'undergone',
    verbItalian: 'subire',
    verbTurkish: 'maruz kalmak, geçirmek',
    verbPresentSimplePronunciation: 'ˌʌndərˈɡoʊ',
    verbPastSimplePronunciation: 'ˌʌndərˈwɛnt',
    verbPastParticiplePronunciation: 'ˌʌndərˈɡɒn',
  },
  {
    verbPresentSimple: 'understand',
    verbPastSimple: 'understood',
    verbPastParticiple: 'understood',
    verbItalian: 'capire',
    verbTurkish: 'anlamak',
    verbPresentSimplePronunciation: 'ˌʌndərˈstænd',
    verbPastSimplePronunciation: 'ˌʌndərˈstʊd',
    verbPastParticiplePronunciation: 'ˌʌndərˈstʊd',
  },
  {
    verbPresentSimple: 'undertake',
    verbPastSimple: 'undertook',
    verbPastParticiple: 'undertaken',
    verbItalian: 'prendere in carico',
    verbTurkish: 'üstlenmek, girişmek',
    verbPresentSimplePronunciation: 'ˌʌndərˈteɪk',
    verbPastSimplePronunciation: 'ˌʌndərˈtʊk',
    verbPastParticiplePronunciation: 'ˌʌndərˈteɪkən',
  },
  {
    verbPresentSimple: 'wake',
    verbPastSimple: 'woke/waked',
    verbPastParticiple: 'woken/waked',
    verbItalian: 'svegliare',
    verbTurkish: 'uyandırmak, uyanmak',
    verbPresentSimplePronunciation: 'weɪk',
    verbPastSimplePronunciation: 'woʊk/weɪkt',
    verbPastParticiplePronunciation: 'ˈwoʊkən/weɪkt',
  },
  {
    verbPresentSimple: 'wear',
    verbPastSimple: 'wore',
    verbPastParticiple: 'worn',
    verbItalian: 'indossare',
    verbTurkish: 'giymek',
    verbPresentSimplePronunciation: 'wɛr',
    verbPastSimplePronunciation: 'wɔr',
    verbPastParticiplePronunciation: 'wɔrn',
  },
  {
    verbPresentSimple: 'weave',
    verbPastSimple: 'wove/weaved',
    verbPastParticiple: 'woven/weaved',
    verbItalian: 'intrecciare',
    verbTurkish: 'dokumak, örmek',
    verbPresentSimplePronunciation: 'wiv',
    verbPastSimplePronunciation: 'woʊv/wiːvd',
    verbPastParticiplePronunciation: 'ˈwoʊvən/wiːvd',
  },
  {
    verbPresentSimple: 'wed',
    verbPastSimple: 'wed/wedded',
    verbPastParticiple: 'wed/wedded',
    verbItalian: 'sposarsi',
    verbTurkish: 'evlenmek',
    verbPresentSimplePronunciation: 'wɛd',
    verbPastSimplePronunciation: 'wɛd/ˈwɛdɪd',
    verbPastParticiplePronunciation: 'wɛd/ˈwɛdɪd',
  },
  {
    verbPresentSimple: 'weep',
    verbPastSimple: 'wept',
    verbPastParticiple: 'wept',
    verbItalian: 'piangere',
    verbTurkish: 'ağlamak',
    verbPresentSimplePronunciation: 'wiːp',
    verbPastSimplePronunciation: 'wɛpt',
    verbPastParticiplePronunciation: 'wɛpt',
  },
  {
    verbPresentSimple: 'weigh',
    verbPastSimple: 'weighed',
    verbPastParticiple: 'weighed',
    verbItalian: 'pesare',
    verbTurkish: 'tartmak, ağırlığında olmak',
    verbPresentSimplePronunciation: 'weɪ',
    verbPastSimplePronunciation: 'weɪd',
    verbPastParticiplePronunciation: 'weɪd',
  },
  {
    verbPresentSimple: 'wend',
    verbPastSimple: 'wended/went',
    verbPastParticiple: 'wended/went',
    verbItalian: 'dirigersi',
    verbTurkish: 'yol almak, ilerlemek',
    verbPresentSimplePronunciation: 'wɛnd',
    verbPastSimplePronunciation: 'wɛndɪd/wɛnt',
    verbPastParticiplePronunciation: 'wɛndɪd/wɛnt',
  },
  {
    verbPresentSimple: 'wet',
    verbPastSimple: 'wet/wetted',
    verbPastParticiple: 'wet/wetted',
    verbItalian: 'bagnare',
    verbTurkish: 'ıslatmak, ıslanmak',
    verbPresentSimplePronunciation: 'wɛt',
    verbPastSimplePronunciation: 'wɛt/ˈwɛtɪd',
    verbPastParticiplePronunciation: 'wɛt/ˈwɛtɪd',
  },
  {
    verbPresentSimple: 'win',
    verbPastSimple: 'won',
    verbPastParticiple: 'won',
    verbItalian: 'vincere',
    verbTurkish: 'kazanmak',
    verbPresentSimplePronunciation: 'wɪn',
    verbPastSimplePronunciation: 'wʌn',
    verbPastParticiplePronunciation: 'wʌn',
  },
  {
    verbPresentSimple: 'withdraw',
    verbPastSimple: 'withdrew',
    verbPastParticiple: 'withdrawn',
    verbItalian: 'ritirare',
    verbTurkish: 'geri çekilmek, geri çekmek',
    verbPresentSimplePronunciation: 'wɪðˈdrɔ',
    verbPastSimplePronunciation: 'wɪðˈdru',
    verbPastParticiplePronunciation: 'wɪðˈdrɔn',
  },
  {
    verbPresentSimple: 'withhold',
    verbPastSimple: 'withheld',
    verbPastParticiple: 'withheld',
    verbItalian: 'trattenere',
    verbTurkish: 'alıkoymak, tutmak',
    verbPresentSimplePronunciation: 'wɪθˈhoʊld',
    verbPastSimplePronunciation: 'wɪθˈhɛld',
    verbPastParticiplePronunciation: 'wɪθˈhɛld',
  },
  {
    verbPresentSimple: 'withstand',
    verbPastSimple: 'withstood',
    verbPastParticiple: 'withstood',
    verbItalian: 'resistere',
    verbTurkish: 'karşı koymak, direnmek',
    verbPresentSimplePronunciation: 'wɪθˈstænd',
    verbPastSimplePronunciation: 'wɪθˈstʊd',
    verbPastParticiplePronunciation: 'wɪθˈstʊd',
  },
  {
    verbPresentSimple: 'wring',
    verbPastSimple: 'wrung',
    verbPastParticiple: 'wrung',
    verbItalian: 'strizzare',
    verbTurkish: 'sıkmak, burkmak',
    verbPresentSimplePronunciation: 'rɪŋ',
    verbPastSimplePronunciation: 'rʌŋ',
    verbPastParticiplePronunciation: 'rʌŋ',
  },
  {
    verbPresentSimple: 'write',
    verbPastSimple: 'wrote',
    verbPastParticiple: 'written',
    verbItalian: 'scrivere',
    verbTurkish: 'yazmak',
    verbPresentSimplePronunciation: 'raɪt',
    verbPastSimplePronunciation: 'roʊt',
    verbPastParticiplePronunciation: 'ˈrɪtn̩',
  },
  {
    verbPresentSimple: 'make',
    verbPastSimple: 'made',
    verbPastParticiple: 'made',
    verbItalian: 'fare',
    verbTurkish: 'yapmak',
    verbPresentSimplePronunciation: 'meɪk',
    verbPastSimplePronunciation: 'meɪd',
    verbPastParticiplePronunciation: 'meɪd',
  },
  {
    verbPresentSimple: 'lean',
    verbPastSimple: 'leant/leaned',
    verbPastParticiple: 'leant/leaned',
    verbItalian: 'inclinare',
    verbTurkish: 'eğilmek, dayanmak',
    verbPresentSimplePronunciation: 'lin',
    verbPastSimplePronunciation: 'lɛnt/lind',
    verbPastParticiplePronunciation: 'lɛnt/lind',
  },
  {
    verbPresentSimple: 'ring',
    verbPastSimple: 'rang',
    verbPastParticiple: 'rung',
    verbItalian: 'suonare',
    verbTurkish: 'çalmak, zil çalmak',
    verbPresentSimplePronunciation: 'rɪŋ',
    verbPastSimplePronunciation: 'ræŋ',
    verbPastParticiplePronunciation: 'rʌŋ',
  },
  {
    verbPresentSimple: 'send',
    verbPastSimple: 'sent',
    verbPastParticiple: 'sent',
    verbItalian: 'inviare',
    verbTurkish: 'göndermek',
    verbPresentSimplePronunciation: 'sɛnd',
    verbPastSimplePronunciation: 'sɛnt',
    verbPastParticiplePronunciation: 'sɛnt',
  },
  {
    verbPresentSimple: 'shine',
    verbPastSimple: 'shone',
    verbPastParticiple: 'shone',
    verbItalian: 'splendere',
    verbTurkish: 'parlamak, ışık saçmak',
    verbPresentSimplePronunciation: 'ʃaɪn',
    verbPastSimplePronunciation: 'ʃɒn',
    verbPastParticiplePronunciation: 'ʃɒn',
  },
  {
    verbPresentSimple: 'wind',
    verbPastSimple: 'wound',
    verbPastParticiple: 'wound',
    verbItalian: 'avvolgere',
    verbTurkish: 'sarmak, dolamak',
    verbPresentSimplePronunciation: 'waɪnd',
    verbPastSimplePronunciation: 'waʊnd',
    verbPastParticiplePronunciation: 'waʊnd',
  },
];
